name: Build, lint and test

on: [pull_request, push]

cache-mode: ${{ github.event_name == 'pull_request' && 'read' || 'write' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 26
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build:all
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test:ci
