name: Build, lint and test

on: [pull_request, push]

jobs:
  build:
    if: github.event_name == 'pull_request'
    cache-mode: read
    runs-on: ubuntu-latest

    steps: &check-steps
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 26
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build:all
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test:ci

  build-push:
    if: github.event_name == 'push'
    cache-mode: write
    runs-on: ubuntu-latest
    steps: *check-steps
