name: Release to NPM Next

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - next-major

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    uses: ./.github/workflows/_changesets-release.yaml
    secrets: inherit
