name: Release to NPM

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - dev
      - "releases/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    uses: ./.github/workflows/_changesets-release.yaml
